"use client";
import {useActionState,useState,useTransition} from 'react';
import Link from 'next/link';
import {accountAction,unblock} from '@/app/conta/actions';
export function AccountSettings({username}:{username:string|null}){
 const [state,action,pending]=useActionState(accountAction,{success:false,message:''});
 return <div className="form"><form action={action} className="panel form"><input type="hidden" name="action" value="username"/><label>Nome de usuário<input name="username" defaultValue={username??''} required minLength={3} maxLength={24} pattern="[a-zA-Z][a-zA-Z0-9_]{2,23}"/></label><p>Use 3 a 24 letras, números ou _, começando por uma letra. Esse usuário é diferente do nome exibido no perfil.</p><button className="button button-primary" disabled={pending}>Salvar usuário</button></form>
 <form action={action} className="panel form"><h2>Trocar senha</h2><input type="hidden" name="action" value="password"/><label>Senha atual<input name="current_password" type="password" autoComplete="current-password" required minLength={8} maxLength={128}/></label><label>Nova senha<input name="password" type="password" autoComplete="new-password" required minLength={8} maxLength={128}/></label><label>Confirme a nova senha<input name="password_confirmation" type="password" autoComplete="new-password" required minLength={8} maxLength={128}/></label><button className="button button-primary" disabled={pending}>Alterar senha</button><Link href="/recuperar-senha">Esqueci minha senha</Link></form>
 <details className="panel"><summary>Excluir minha conta definitivamente</summary><p>Esta ação remove sua conta, fotos, conversas associadas, mensagens e avaliações. As outras pessoas também perderão o histórico das conversas com você. Não é possível desfazer.</p><form action={action} className="form"><input type="hidden" name="action" value="delete"/><label>Senha atual<input name="current_password" type="password" autoComplete="current-password" required minLength={8} maxLength={128}/></label><label>Digite EXCLUIR MINHA CONTA<input name="confirmation" required pattern="EXCLUIR MINHA CONTA" autoComplete="off"/></label><button className="button interest" disabled={pending}>Excluir definitivamente</button></form></details><p className="notice" role="status">{state.message}</p></div>;
}
export function BlockedList({items}:{items:{target_id:string;display_name:string|null}[]}){
 const [notice,setNotice]=useState('');const [pending,start]=useTransition();
 return <section className="panel"><p>Desbloquear permite novos contatos, mas não reabre conversas encerradas. Um bloqueio feito pela outra pessoa continua valendo.</p>{items.length?items.map(item=><div className="button-row" key={item.target_id}><span>{item.display_name??'Perfil indisponível'}</span><button className="button button-secondary" disabled={pending} onClick={()=>start(async()=>{const result=await unblock(item.target_id);setNotice(result.error??'Perfil desbloqueado.');})}>Desbloquear</button></div>):<p>Você não bloqueou ninguém.</p>}<p className="notice" role="status">{notice}</p></section>;
}
