import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { db, alice, bob, carol, banned, incomplete, unconfirmed, asUser, rpc, safety, block } from './connections-fixture.mjs';
await asUser(alice);
await rpc('rate',bob,{score:4,visibility:'profile'});
const reportPayload={subject:'profile',reason:'spam',details:'Relato privado',request_id:randomUUID()};
const report=(await safety('report',bob,reportPayload)).id;
assert.equal((await safety('report',bob,reportPayload)).id,report);
assert.equal((await safety('reports')).length,1);
assert.equal((await safety('reports'))[0].accused,undefined);
assert.equal((await safety('reports'))[0].reporter,undefined);
await assert.rejects(safety('report',bob,{...reportPayload,reason:'unknown'}),/motivo/);
await assert.rejects(safety('report',bob,{...reportPayload,details:'x'.repeat(1001)}),/1.000/);
await assert.rejects(safety('report',alice,reportPayload),/outra pessoa/);
await asUser(bob);
assert.deepEqual(await safety('reports'),[]);
const review=(await rpc('reputation',bob)).reviews[0];
assert.ok(review.id);
await safety('report',review.id,{...reportPayload,subject:'first_impression',request_id:randomUUID()});
await db.exec('reset role');
await db.query("update duoeto_private.reports set status='reviewing' where id=$1",[report]);
await asUser(alice);
let notices=await safety('notifications');
assert.equal(notices.length,1);assert.equal(notices[0].kind,'report_updated');
assert.equal(notices[0].body,undefined); assert.equal(notices[0].peer,undefined);
const noticeId=notices[0].id;
await asUser(bob);
await safety('read_notification',null,{id:noticeId});
await asUser(alice);
assert.equal((await safety('notifications'))[0].read_at,null);
await safety('read_notification',null,{id:noticeId});
assert.ok((await safety('notifications'))[0].read_at);
const contact=(await rpc('send',bob,{body:'Mensagem privada'})).id;
await asUser(bob);
notices=await safety('notifications');assert.equal(notices[0].kind,'contact_received');
assert.equal(JSON.stringify(notices).includes('Mensagem privada'),false);
await asUser(carol);
await assert.rejects(safety('report',contact,{...reportPayload,subject:'contact'}),/indisponível/);
await assert.rejects(safety('report',review.id,{...reportPayload,subject:'first_impression'}),/indisponível/);
await asUser(bob);
await safety('report',contact,{...reportPayload,subject:'contact',request_id:randomUUID()});
const chat=(await rpc('accept',contact)).id;
await asUser(alice);
assert.equal((await safety('notifications'))[0].kind,'contact_accepted');
const messageRequest=randomUUID();
await rpc('message',chat,{body:'Texto que não sai em notificação',request_id:messageRequest});
await rpc('message',chat,{body:'Texto que não sai em notificação',request_id:messageRequest});
await asUser(bob);
notices=await safety('notifications');assert.equal(notices.filter(n=>n.kind==='message').length,1);
assert.equal(JSON.stringify(notices).includes('Texto que'),false);
await safety('report',chat,{...reportPayload,subject:'conversation',request_id:randomUUID()});
await asUser(carol);
await assert.rejects(safety('report',chat,{...reportPayload,subject:'conversation'}),/indisponível/);
await asUser(alice);await rpc('close',chat);
await asUser(bob);
assert.equal((await safety('notifications'))[0].kind,'conversation_closed');
// A refusal notifies the sender without exposing the contact body.
await asUser(alice); const declined=(await rpc('send',bob,{body:'Outro contato'})).id;
await asUser(bob);await rpc('decline',declined);
await asUser(alice);assert.equal((await safety('notifications'))[0].kind,'contact_declined');
// A reverse contact remains allowed after directional refusal.
await asUser(bob); await rpc('rate',alice,{score:5,visibility:'private'});
const reverse=(await rpc('send',alice,{body:'Contato reverso'})).id;
await asUser(alice);const active=(await rpc('accept',reverse)).id;
await db.exec('reset role');
const before=(await db.query('select count(*)::int as n from duoeto_private.notifications')).rows[0].n;
await asUser(bob);await block(bob,alice);
assert.deepEqual(await safety('notifications'),[]);
// Reporting your own blocked contact stays available for moderation evidence.
await safety('report',active,{...reportPayload,subject:'conversation',request_id:randomUUID()});
await db.exec('reset role');
assert.equal((await db.query('select count(*)::int as n from duoeto_private.notifications')).rows[0].n,before);
await asUser(alice);
assert.deepEqual((await safety('notifications')).map(n=>n.kind),['report_updated']);
for (const table of ['reports','notifications']) await assert.rejects(db.exec(`select * from duoeto_private.${table}`),/permission denied/);
await assert.rejects(db.query("update duoeto_private.reports set status='resolved' where id=$1",[report]),/permission denied/);
for (const id of [banned,incomplete,unconfirmed,'']) {
 await asUser(id); await assert.rejects(safety('notifications'),/Complete/);await assert.rejects(safety('report',bob,reportPayload),/Complete/);
}
await db.exec('reset role; set role anon');
await assert.rejects(safety('notifications'),/permission denied/);
await assert.rejects(safety('report',bob,reportPayload),/permission denied/);
await db.close();
console.log('PASS: denúncias privadas/idempotentes, motivos/limites, autorização por conteúdo, status, notificações sem texto, leitura restrita, eventos únicos e bloqueio sem notificação.');
